language: objective-c
osx_image: xcode7.2
before_script:
    - brew update 
    - brew outdated xctool || brew upgrade xctool
script:
    - xctool test -project STPopupPreviewExample/STPopupPreviewExample.xcodeproj -scheme STPopupPreviewExample -sdk iphonesimulator
